Documentation:
  Enabled: false

LineLength:
  Max: 120

Lint/RescueException:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise
  SupportedStyles:
    - only_raise
    - only_fail
    - semantic

Metrics/AbcSize:
  Max: 19

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 16

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 9

Naming/VariableNumber:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Performance/TimesMap:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false
