language: ruby
rvm:
  - 1.9.3
  - 2.1.7
  - 2.2.3
  - jruby-19mode
  - jruby-head
  - rbx-2
  - ruby-head

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-head

before_install:
  - gem update --system
  - gem install bundler -v 1.10.6
install: 'bundle'
script: 'bundle exec rspec && bundle exec rubocop'
notifications:
    email:
        - pedro.carrico@gmail.com
